using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Net.Http;
using System.Windows.Forms;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WindowsFormsApp1;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace WindowsFormsApp1
{
    public class Weather
    {
        public Weather(string UrlBase)
        {
            ClienteHttp.BaseAddress = new Uri(UrlBase);
        }

        readonly HttpClient ClienteHttp = new HttpClient();

        public List<Country> LocationSearch(bool Query, string Arguments)
        {
            List<Country> C = null;
            if (Arguments != "")
            {
                var Q = Query ? "query" : "lattlong";
                var Request = ClienteHttp.GetAsync($"/api/location/search/?{Q}={Arguments}").Result;
                if (Request.IsSuccessStatusCode)
                {
                    var ResultString = Request.Content.ReadAsStringAsync().Result;
                    C = JsonConvert.DeserializeObject<List<Country>>(ResultString);
                }
            }
            return C;
        }
        public Country WeatherLocation(string Woeid)
        {
            Country C = null;
            if (Woeid != "")
            {
                var Request = ClienteHttp.GetAsync($"/api/location/{Woeid}/").Result;
                if (Request.IsSuccessStatusCode)
                {
                    var ResultString = Request.Content.ReadAsStringAsync().Result;
                    C = JsonConvert.DeserializeObject<Country>(ResultString);
                }
            }
            return C;
        }
        //public string Images(string Abbreviation) => "https://www.metaweather.com/static/img/weather/ico/"+Abbreviation+".ico";
        public string Images(string Abbreviation) => $@"C:\Users\Erick\Downloads\Cursos-Proyectos\curso c#\WindowsFormsApp1\WindowsFormsApp1\Imagenes\{Abbreviation}.ico";
    }
    public class Country
    {     
        public string title { get; set; }
        public string location_type { get; set; }
        public string latt_long { get; set; }
        public int woeid { get; set; }
        public int distance { get; set; }
        public List<Country> consolidated_weather { get; set; }
        public string humidity { get; set; }
        public string applicable_date { get; set; }
        public string weather_state_name { get; set; }
        public string weather_state_abbr { get; set; }
        public double wind_direction { get; set; }
        public double the_temp { get; set; }
        public double min_temp { get; set; }
        public double max_temp { get; set; }
        public double visibility { get; set; }
    }
}

